<?xml version="1.0"?>
<robot name="arlobot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Macro for ArloBot body. -->

  <!-- original radius 0.0762 original width 0.03175-->
  <property name="wheel_radius" value="0.0775" />
  <property name="wheel_width" value="0.0388" />
  <property name="plate_height" value="0.1085" />
  <property name="axis_height" value="${wheel_radius - plate_height}" />
  <property name="wheel_base" value="0.160" />

  <property name="base_x" value="0.33" />
  <property name="base_y" value="0.33" />

  <xacro:macro name="arlo_base">
    <material name="Green">
      <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    <material name ="veryDarkGrey">
      <color rgba=".2 .2 .2 1"/>
    </material>
    <material name ="light_grey">
      <color rgba="0.6 0.6 0.6 1"/>
    </material>

    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
        <material name="Green" />
      </visual>
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
      </inertial>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.10125" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link" />
    </joint>

    <link name="base_link">
      <inertial>
        <mass value="2" />
        <origin xyz="0 0 0.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.0095" radius="0.2245"/>
        </geometry>
        <material name ="veryDarkGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.0095" radius="0.2245"/>
        </geometry>
      </collision>
    </link>

    <link name="front_caster_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="-1.5707 0 1.5707" />
        <geometry>
          <mesh filename="package://papa_description/meshes/caster-wheel.stl"/>
        </geometry>
        <material name ="light_grey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
    </link>

    <joint name="front_caster_joint" type="fixed">
      <origin xyz="0.18745 0 -0.00475" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="front_caster_link" />
    </joint>

    <link name="rear_caster_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="-1.5707 0 1.5707" />
        <geometry>
          <mesh filename="package://papa_description/meshes/caster-wheel.stl"/>
        </geometry>
        <material name ="light_grey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
    </link>

    <joint name="rear_caster_joint" type="fixed">
      <origin xyz="-0.18745 0 -0.00475" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="rear_caster_link" />
    </joint>

    <link name="left_wheel_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
        <geometry>
          <cylinder radius="${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <material name ="black" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
        <geometry>
          <cylinder radius="${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- Fixed because we never rotate it anyway, it is just for show -->
    <!-- NOTE This may prevent gazebo from working with this model -->
    <joint name="left_wheel_joint" type="continuous">
      <axis xyz="0 1 0"/>
      <limit effort="10000.0" velocity="2"/>
      <origin xyz="0 -${wheel_base} ${axis_height}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
    </joint>

    <link name="right_wheel_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
          iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
        <geometry>
          <cylinder radius="0.0762" length = "0.03175"/>
        </geometry>
        <material name ="black" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
        <geometry>
          <cylinder radius="0.0762" length = "0.03175"/>
        </geometry>
      </collision>
    </link>

    <joint name="right_wheel_joint" type="continuous">
      <axis xyz="0 1 0"/>
      <limit effort="10000.0" velocity="2"/>
      <origin xyz="0 ${wheel_base} ${axis_height}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
    </joint>
  </xacro:macro>
</robot>
