#!/usr/bin/env python                                                                                                                                               
                                                                                                                                                                    
import rospy                                                                                                                                                        
import tf                                                                                                                                                           
import tf2_ros                                                                                                                                                      
import tf.msg
from tf import TransformListener                                                                                                                                    
from std_msgs.msg import Header
import geometry_msgs.msg                                                                                                                                     
from geometry_msgs.msg import Transform, TransformStamped                                                                                                           
                                                                                                                                                                    
tf_pub = tf2_ros.TransformBroadcaster()                                                                                                             
def tf_callback(data):
    #for t in data.transforms:
       # print t
        if 'start_of_service' in t.header.frame_id and 'device' in t.child_frame_id:
            print "hola"
            tf_odom_map = t                                                                                                                                          
            tf_odom_map.header.frame_id = 'map'                                                                                                                         
            tf_odom_map.child_frame_id = 'base_footprint'                                                                                                               
            tf_odom_map.header.stamp = rospy.Time.now()                                                                                                                 
            tf_pub.sendTransform(tf_odom_map)                                                                                                                           
                                                                                                                                                                    
if __name__== "__main__":                                                                                                                                           
                                                                                                                                                                    
    # ROS init name                                                                                                                                                 
    rospy.init_node('odom_tf_publisher', anonymous=True)                                                                                                            
                                                                                                                                                                    
    # Subscribe to TF topic                                                                                                                                         
    rospy.Subscriber("/tango/transform/start_of_service_T_device", TransformStamped, tf_callback)                                                                                                                 
                                                                                                                                                                    
    rospy.spin()  
